### ISSUE TITLE
Power Button Reassignment Please :-(

### ISSUE THREAD

**Issue by yaelboy36** [shchmue/Lockpick_RCM#57] opened 2021-05-20 00:39 UTC
My switch's power button is completely nonfunctional (Hardware level, on board, not the ribbon/button) Is there a way to make it so + moves menu, and - is the selector?

**Comment by shchmue** [comment] 2021-05-20 17:15
closing as dupe of #31

**Closed by shchmue** 2021-05-20 17:15 UTC
