### ISSUE TITLE
package1_key_01 - package1_key_05 cant be found in prod.keys.

### ISSUE THREAD

**Issue by weigeloveu** [shchmue/Lockpick_RCM#80] opened 2022-10-21 09:32 UTC
ips patch creator need package1_key_01 - package1_key_05,but i can’t found it in prod.keys,only the package2 key.

**Comment by shchmue** [comment] 2022-10-25 00:40
I don't know what ips patch creator is but I'd be very surprised if it actually needed package1 keys. A Mariko console can't dump them. If your console is Erista, you dumped your `prod.keys` file using Lockpick_RCM, and those keys are not present, then you should have seen keyblob errors. This would indicate that at some point you corrupted the contents of your BOOT0 partition. I can't think of any reason this would be caused by Lockpick_RCM so I'm closing this and I'll suggest asking whoever maintains ips patch creator.

**Closed by shchmue** 2022-10-25 00:40 UTC
